sudo: required #whenever using docker sudo requried for super user
services:
    - docker

before_install:
    - docker build -t pritambiswas00/react-prod -f Dockerfile.dev .

script:
    - docker run -e CI=true pritambiswas00/react-prod npm run test 